# CONFIG FOR VQ-VAE MODEL

data:
  embeddings_paths:
  - 'data/embeddings_ALE_Pong-v5_cnn.npy'
  - 'data/embeddings_ALE_Breakout-v5_cnn.npy'
  - "data/embeddings_ALE_MsPacman-v5_cnn.npy"
  output_dir: 'data'

model:
  input_dim: 384        # VQ in
  latent_dim: 128       # VQ out 
  num_codes: 256        # Codebook Size
  commitment_cost: 0.25 # VQ Loss Weight

training:
  batch_size: 256
  num_epochs: 50
  learning_rate: 1.0e-3
  weight_decay: 1.0e-4
  val_split: 0.05

seed: 42

